"""added indexes to filter

Revision ID: b5e06189df89
Revises: 94377324c1d2
Create Date: 2025-12-18 08:57:57.844886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e06189df89'
down_revision = '94377324c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_updated_at'))
        batch_op.drop_index(batch_op.f('ix_issue_title'))
        batch_op.drop_index(batch_op.f('ix_issue_status'))
        batch_op.drop_index(batch_op.f('ix_issue_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_issue_project_id'))
        batch_op.drop_index(batch_op.f('ix_issue_priority'))
        batch_op.drop_index(batch_op.f('ix_issue_id'))
        batch_op.drop_index(batch_op.f('ix_issue_due_date'))
        batch_op.drop_index(batch_op.f('ix_issue_description'))
        batch_op.drop_index(batch_op.f('ix_issue_created_at'))
        batch_op.drop_index(batch_op.f('ix_issue_assignee_id'))

    # ### end Alembic commands ###
