"""Added memebrs model

Revision ID: e1c86f2b47e6
Revises: b5e06189df89
Create Date: 2025-12-18 09:12:37.542171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c86f2b47e6'
down_revision = 'b5e06189df89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_member_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_member_user_id'))

    op.drop_table('project_member')
    # ### end Alembic commands ###
